/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../EntityId';

import { PostNestedInput } from './PostNestedInput';

// <keep-imports>
// </keep-imports>

@InputType()
export class PostEditInput {
  @Field(() => EntityIdScalar)
  public id: EntityId;

  @Field(() => String, { nullable: true })
  public text?: string | null;

  @Field(() => String, { nullable: true })
  public title?: string | null;

  @Field(() => PostNestedInput, { nullable: true })
  public parentPost?: PostNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
