/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../EntityId';

import { PostNestedInput } from './PostNestedInput';

// <keep-imports>
// </keep-imports>

@InputType()
export class VoteNestedInput {
  @Field(() => EntityIdScalar, { nullable: true })
  public id?: EntityId;

  @Field(() => Number, { nullable: true })
  public sentiment?: number | null;

  @Field(() => PostNestedInput, { nullable: true })
  public post?: PostNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
