/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length no-duplicate-imports
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, OneToMany, OneToOne, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

import { User } from './User';
import { Vote } from './Vote';

import { asPromise } from '../../utils/as-promise';
import * as auth from '../../utils/auth/auth-checkers';
import { IAuthorizable } from '../../utils/auth/IAuthorizable';
import { getInputOperationType } from '../../utils/get-input-operation-type';
import { noChange } from '../../utils/no-change';
import { PostAuth } from '../auth/PostAuth';
import { EntityId, EntityIdScalar } from '../EntityId';
import { PostCreateInput } from '../inputs/PostCreateInput';
import { PostEditInput } from '../inputs/PostEditInput';
import { PostNestedInput } from '../inputs/PostNestedInput';
import { IRequestContext } from '../IRequestContext';
import { updateParentPostRelation } from './update-operations/post-update-operations';

// <keep-imports>
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class Post implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  public id: EntityId;

  public authorizationChecker = new PostAuth(this);

  @Field(() => String)
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public text: string;

  @Field(() => String, { nullable: true })
  @Column({nullable: true, type: 'varchar',
    // <custom-column-args>
    // </custom-column-args>
  })
  public title?: string | null;

  @ManyToOne(() => User, (user) => user.posts , { nullable: false, onDelete: 'CASCADE' })
  @Field(() => User , { nullable: false })
  public author: Promise<User>;

  @ManyToOne(() => Post, (post) => post.childPosts , { nullable: true, onDelete: 'SET NULL' })
  @Field(() => Post , { nullable: true })
  public parentPost: Promise<Post | undefined | null>;

  @OneToMany(() => Vote, (vote) => vote.post)
  @Field(() => [Vote])
  public votes: Promise<Array<Vote>>;

  @OneToMany(() => Post, (post) => post.parentPost)
  @Field(() => [Post])
  public childPosts: Promise<Array<Post>>;

  @CreateDateColumn()
  @Field()
  public createdAt: Date;

  @UpdateDateColumn()
  @Field()
  public updatedAt: Date;

  public async update(input: PostCreateInput | PostEditInput | PostNestedInput, context: IRequestContext) {
    const { parentPost, ...data } = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    if (getInputOperationType(this, input) === 'create') {
      this.author = asPromise(await this.author || await context.user);
    }
    await updateParentPostRelation(this, parentPost, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  // </keep-methods>
}
