/*** THIS FILE US AUTOGENERATED BY apollox, DON'T EDIT IT MANUALLY ***/

/* tslint:disable */
import { mutation, query } from './client';
import * as T from './types';

import { CreatePost } from './generated-queries/create-post-queries';
import { Login } from './generated-queries/login-queries';
import { Posts } from './generated-queries/posts-queries';

export class GraphqlStore {
  public createPost = mutation<T.CreatePostVariables, T.CreatePost>(CreatePost);
  public login = mutation<T.LoginVariables, T.Login>(Login);
  public posts = query<{}, T.Posts>(Posts);
}

export const graphqlStore = new GraphqlStore();