/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length
import { asPromise } from '../../../utils/as-promise';
import { PostNestedInput } from '../../inputs/PostNestedInput';
import { IRequestContext } from '../../IRequestContext';
import { Post } from '../Post';

export async function updateParentPostRelation(post: Post, parentPost: PostNestedInput | null | undefined, context: IRequestContext) {
  const existingParentPost = await post.parentPost;

  if (parentPost === null) {
    post.parentPost = Promise.resolve(null);
  } else if (parentPost === undefined) {
    // do nothing
  } else if (parentPost.id) {
    const parentPostModel = await context.em.findOneOrFail(Post, parentPost.id);
    post.parentPost = asPromise(await parentPostModel.update(parentPost, context));
  } else if (existingParentPost) {
    await existingParentPost.update(parentPost, context);
  } else {
    post.parentPost = asPromise(await new Post().update(parentPost, context));
  }
}
